### ISSUE TITLE
navbar INPUT_GROUP height

### ISSUE THREAD

**Issue by tgs-1** [Servoy/bootstrapextracomponents#1]
The height of the navbar INPUT_GROUP menuItem is different!
![navbar_input_group](https://cloud.githubusercontent.com/assets/8092969/24095708/9e0c9a2a-0d5e-11e7-9b0d-e9654d4c7a81.png)
This are my properties set:
itemId: "1",
dataProvider: find_txt,
displayType: "INPUT_GROUP",
iconName: "fa fa-search",
onAction: onAction_find,
position: "LEFT",
isActive: "true",
text: "Enter search"

I would like to have the same height of the group items.

**Comment by pruhsert** [comment]
Interesting. That does not happen in the sample solution at my machine.

![image](https://cloud.githubusercontent.com/assets/6121942/24096142/9f60eb54-0d60-11e7-936a-85da5fc6f41a.png)

Could you try that with the sample solution and see if you get the same result?

**Comment by tgs-1** [comment]
I have tested the sample solution with the same result.
But I have detected that it is a browser issue.
With e.g. Firefox the INPUT_GROUP has a identical height, with Opera not.

**Comment by pruhsert** [comment]
I don't have opera, but it is OK on Chrome, Firefox and Edge. Not sure it's worth investigating this...

**Comment by pruhsert** [comment]
Just tested it on Opera and internet explorer and no issue there as well.

![image](https://cloud.githubusercontent.com/assets/6121942/24139616/0c9236bc-0e1d-11e7-9ab9-d84039dfee4c.png)

So I think I will close this?
