### ISSUE TITLE
visible attribute has no function

### ISSUE THREAD

**Issue by ExplectMartijn** [Servoy/bootstrapextracomponents#13]
if visible set to false switch-element is hidden in developer, but still visible in browser

**Comment by pruhsert** [comment]
with which component have you tried that?

**Comment by ExplectMartijn** [comment]
the switch, sorry thought I added it at switch

Op 9-8-2017 om 18:27 schreef Patrick Ruhsert:

**Comment by tuanway** [comment]
Fixed. This should be working in the next release.
