### ISSUE TITLE
Switch animation not working on Safari (Mac)

### ISSUE THREAD

**Issue by ErosN** [Servoy/bootstrapextracomponents#15]
The switch animation is not working when clicking on the switch. The onClick even is called, but the animation is not changing from On to Off or vice versa.

**Comment by tuanway** [comment]
This is working for me for (macOS Sierra w/ Safari v11).

Can you specify which version of OS and safari you were having issues with?

Also make sure to check if you are on the **latest** version of the component.

**Comment by ErosN** [comment]
This is working with the latest version of bootstrap extra components.
