### ISSUE TITLE
navbar subMenuItems not displayed by the menuItem

### ISSUE THREAD

**Issue by tgs-1** [Servoy/bootstrapextracomponents#16]
If I click on a navbar menuItem for the subMenuItems list on a form in dialog, displayed in the center of the main form by default, the subMenuItems are displayed far away from the menuItem!?
Please have a look to my screenshots. I'm on Servoy 8.2.1.
![menu_item_1](https://user-images.githubusercontent.com/8092969/31485555-87e4e6da-af34-11e7-8820-ee9d1f325dae.png)
![menu_item_2](https://user-images.githubusercontent.com/8092969/31485564-930ba0bc-af34-11e7-831b-44d0db96545b.png)
![menu_item_3](https://user-images.githubusercontent.com/8092969/31485569-986ec372-af34-11e7-8351-0adfda26842d.png)

**Comment by pruhsert** [comment]
Should be fixed in the next release
