### ISSUE TITLE
In the included demo project, the plain Drop Down Link example does not work. Styles are messed up for the Drop Down Buttons.

### ISSUE THREAD

**Issue by bluegrassrules** [Servoy/bootstrapextracomponents#23]
Clicking on the Drop down link does nothing.  Drop button (blue) and Drop split button (red) do not display correctly.
<img width="507" alt="screen shot 2018-03-09 at 1 46 59 pm" src="https://user-images.githubusercontent.com/20289132/37224116-842e1562-23a0-11e8-8a01-9256a57fe52f.png">
I have tried other browsers - same problem.

**Comment by pruhsert** [comment]
I think the appearance comes from the style class applied to the wrong property. We had the same issue in the sample solution. The component has a styleClass property to style the whole and a buttonStyleClass property to just address the button. The above screenshot looks like the styleClass is set to btn-primary while that should be on the buttonStyleClass property and the styleClass property should be left empty.

In my tests the button action works fine.
