### ISSUE TITLE
markClickedItemActive

### ISSUE THREAD

**Issue by raymondf1977** [Servoy/bootstrapextracomponents#24]
Hi,

On the Bootstrap Extra Components (v.1.2.4) the Navbar property 'markClickedItemActive'
does not function properly. (it never gets set 'IsActive')

Therefor the 'getSelectedMenu' always returns null on the Action event.
When 1 item is set to IsActive manually, and than an item is clicked, it does work.

Regards,
Raymond

**Comment by pruhsert** [comment]
That should be fixed with the next release
