### ISSUE TITLE
Nav

### ISSUE THREAD

**Issue by philippr71** [Servoy/bootstrapextracomponents#26]
Hi

Try to use the NavBar-Component (Bootstrap Extra Component Version 1.2.5). Want to execute some stuff when I click on a Menu-Item. But nothing happens. The "OnBrandClicked"-Event fires as expected but the "onMenuItemClicked" doesn't fire and also not the  "onAction"-Event on the Menu-Items themselves.

In the Browser-Console I got the following Errors when I click on a Menu-Item:

![image](https://user-images.githubusercontent.com/12142061/45220053-3a2e4f80-b2ad-11e8-9ed8-a98dfcacce8d.png)

**Comment by pruhsert** [comment]
That should be fixed in the master branch and available with the next release.
