### ISSUE TITLE
INPUT_GROUP height problem

### ISSUE THREAD

**Issue by og1** [Servoy/bootstrapextracomponents#28]
I am having trouble to get the INPUT_GROUP to display correctly as you can see in the image below. 

There are two problems:

1. The height of the controls differs (this was reported earlier see issue #1)
2. Some parts have thicker edges to the left and right which makes it look smudgy

![image](https://user-images.githubusercontent.com/8705637/47004317-8f257700-d131-11e8-843e-dd82e78eb671.png)

The first problem seems to be browser related since it does occur in Chrome and not in FireFox. Since most people use Chrome it would be very nice if this could be fixed.

The second problem occurs in all browsers, including the servoy demo solution.

To rule out any CSS interference I also tried it without any CSS in my solution but the problem persisted. **Note**: when running the demo solution from demo.servoy.com it works as expected even in Chrome but when you download the solution and run it in a separate workspace, it does not?

**Comment by pruhsert** [comment]
As I said in the case you referring to (which is about the nav bar), I cannot reproduce the height problem. I'm using the latest Chrome and I looked at it in Firefox as well. And I have used the sample solution.

The "double" border can be addressed. Although it is standard bootstrap, I have added a "fix" for that for the next release. I guess that in general it is quite uncommon to have more than one addon.

**Comment by og1** [comment]
Hi Patrick,

I am on Mac maybe it is a Mac/retina related problem. I will build a sample solution and deploy it on a windows server. If it is not a problem there then it’s ok, otherwise I will send it to you. Thanks.

Kind regards,

Omar van Galen             


06-2 12345 86
omar@intrasoft.nl <mailto:omar@intrasoft.nl>
