### ISSUE TITLE
INPUT_GROUP readonly property does not work

### ISSUE THREAD

**Issue by og1** [Servoy/bootstrapextracomponents#29]
When the readonly property is set to true it is still possible to edit the contents of the field. Setting enabled to false works as expected.

**Comment by pruhsert** [comment]
To align this a bit better with other servoy components, I have changed that now:

1. you have now have a editable property, that you can set at design time; text input will be disabled, but buttons can be clicked
2. readOnly has been made a runtime only property, so it can no longer be set in designer

Changes will be available with the next release
