### ISSUE TITLE
navbar > brandLogo events

### ISSUE THREAD

**Issue by tgs-1** [Servoy/bootstrapextracomponents#3]
It would be nice, if we could get onAction events and so on for brandLogo on the navbar.

**Comment by pruhsert** [comment]
What do you mean by "so on"? Would an event onBrandLogoClicked be good enough? I could fire a method with onMenuItemClicked, but what item to provide then, so I guess we will need an extra handler for that.

**Comment by tgs-1** [comment]
An onBrandLogoClicked would be fine and enough for me!
With "so on" I meant things they are possible and relative easy for you to do.

**Comment by pruhsert** [comment]
Version 1.1.1 has an onBrandClicked event

**Comment by tgs-1** [comment]
Sorry for the delay, but could it also be possible to add a tooltip property to brandLogo?
