### ISSUE TITLE
floatlabel textbox does not compile "type="password""

### ISSUE THREAD

**Issue by r4inX** [Servoy/bootstrapextracomponents#46]
Updates servoy to 2022.12.0.3823 and all compoments to 2022.12. Now trying to create a form with floatlabel-textboxes and as inputType i set "password" (or password-with-eye). Servoy does not compile it to the finished form in browser and ng-desktop. 

I remember there was the same bug with non-float textboxes. 

-Rain

**Comment by jcompagner** [comment]
what do you mean it doesn't compile?
what do you get? what is the exception? what does the ng build console say?

**Comment by r4inX** [comment]
the exception is that it does not matter if i say the inputtype is text, email or passwort. In the complied HTML (inspected in the browser inspector) the html property "type="XXX"" is missing for floatlabel-text. In my example of floatlabe-text-password the text is not hidden in the textbox. i added some screenshots. 

In Screenshot_4 i marked whats missing, if i add that in the browser-inspector it works. 

![floatlabel_2](https://user-images.githubusercontent.com/28804733/211854735-f663f19c-2029-4598-9594-e61e64f31064.png)
![floatlabel_1](https://user-images.githubusercontent.com/28804733/211854739-1e4b3df4-af6a-4eab-9fc9-c2c64d0a128b.png)
![floatlabel_how_it_should_be](https://user-images.githubusercontent.com/28804733/211854740-75ca08ed-2471-4b33-8584-6b2ac34c9e44.png)
![floatlabel_3](https://user-images.githubusercontent.com/28804733/211854742-6a418c64-64a1-40a8-9237-ed849db0ed81.png)

**Comment by r4inX** [comment]
@jcompagner any news about that? our solution is going in production in a few days. As a "workaround" im now using the normal text-fields (not the floatlabel). However i find the floatlabel ones alot better design-wise. Its not a blocker but is still appreciated. Have a nice week.

-rain

**Comment by jcompagner** [comment]
this is fixed by this commit:

https://github.com/Servoy/bootstrapcomponents/commit/b42cfed9566c40d08be23984cefcde2dbdba0093
