### ISSUE TITLE
Drop Down duplicate error servoy version 2023.03

### ISSUE THREAD

**Issue by juanetec** [Servoy/bootstrapextracomponents#49]
Hi,
I found an error with Form Container that I have a Drop Down.
I found this ticket below, look like the same problem but in another component:

https://support.servoy.com/browse/SVY-18133

Could you check that?

Un Saludo
Juan Ramírez

**Comment by jcompagner** [comment]
are you talking about the exactly same error as that case? so this?

TypeError: Cannot set properties of undefined (setting 'elUnwatch')
    at CustomArrayType.addBackWatches (array.js:360:47)

do you still have that with 2023.3.1 ?

**Comment by juanetec** [comment]
"_are you talking about the exactly same error as that case? so this?_"
yes it was.

do you still have that with 2023.3.1 ?
No, is fixed.

Thanks
