### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by tuanway** [Servoy/bootstrapextracomponents#5]
Is there support for the hamburger menu? (mobile support)

![image](https://cloud.githubusercontent.com/assets/7150474/26069452/2f2a07e0-39a1-11e7-8e83-d0f8dfb6890f.png)

**Comment by pruhsert** [comment]
That is currently disabled and needs to be investigated if needed.

**Comment by tuanway** [comment]
Yes. Would be great to have available.

**Comment by pruhsert** [comment]
That should work with the next release. There you have a collapsible property, that you can set to true.
