### ISSUE TITLE
Navbar onMenuItemClicked and menu item onAction assignment not working

### ISSUE THREAD

**Issue by iangus** [Servoy/bootstrapextracomponents#9]
Setting the onMenuItemClicked event:
![image](https://user-images.githubusercontent.com/16198817/26844592-f021913a-4ac1-11e7-8bb2-0f3723a7f383.png)

or the menu item onAction event:
![image](https://user-images.githubusercontent.com/16198817/26844645-218968b0-4ac2-11e7-816c-de8df80cf90f.png)

doesn't appear to be working. Clicking any of the menu items does nothing.

Here is the method code:
![image](https://user-images.githubusercontent.com/16198817/26845075-6c5f34cc-4ac3-11e7-877a-8d45eeefa207.png)

Using bootstrap extra components package version 1.1.2 downloaded from the web package manager

This was an issue in servoy 8.1.2 and continues to be an issue in 8.1.4

**Comment by iangus** [comment]
Sample solution can be found here: https://drive.google.com/open?id=0B19qK6lMUREzbmhsRmlRZTAtekE

**Comment by tuanway** [comment]
The itemId property must be filled in.  Please give that a try first.

**Comment by iangus** [comment]
Ah that was the issue. Thanks
